#服务器端口设置
server:
  port: 8080
  #项目路径
#  servlet:
#    context-path: /bdf
  #是否打印sql语句
spring:
  jpa:
   showSql: true
   database-platform: org.hibernate.dialect.MySQL5Dialect
  #hibernate反向创建表设置，update启动时更新表结构，create 启动时重新创建表结构，none 启动时不检查
   hibernate.ddl-auto: none
  #hibernate字段命名规则
   hibernate.naming.physical-strategy : org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
   properties:
     hibernate:
       current_session_context_class=org:
         springframework:
           orm:
             hibernate5:
               SpringSessionContext
  #springboot热部署设置，添加文件改动不重启目录。
  devtools:
    restart:
      additional-exclude: com/**

  #数据库脚本的编码设置为UTF-8
  datasource:
    sql-script-encoding: UTF-8
    #数据源配置，pom中需要引入对应的数据库jdbc依赖
    continue-on-error: true
    url: jdbc:mysql://localhost:3306/bdf3?autoReconnect=true&useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=CONVERT_TO_NULL&useSSL=false&serverTimezone=Asia/Shanghai
    username: root
    password: 123456
    driver-class-name: com.mysql.jdbc.Driver
    #如果数据库为非嵌入式数据库，这个属性第一次启动的时候一定要设置为ALWAYS，用于初始化数据，初始化好后，可以关闭，也可以不关闭，有自己决定 NEVER
    initialization-mode: Never

